# Generated by Django 4.1.4 on 2022-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, to='product.image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
