# Generated by Django 4.1.4 on 2022-12-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_item_images_alter_item_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
