# Generated by Django 4.1.4 on 2022-12-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(to='product.image'),
        ),
    ]
