# Generated by Django 4.1.4 on 2022-12-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_item_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
